// ======================================================================
// Recommendation Service
//
// Purpose:
// Handles storing personalized activity recommendations generated by AI.
// These are used later to show suggested activities to the user.
//
// Called from Inngest generateActivityRecommendations()
// ======================================================================

import { Recommendation } from "../models/Recommendation";
import { logger } from "../utils/logger";

// ----------------------------------------------------------------------
// Save recommendations for a specific user
// ----------------------------------------------------------------------
export const saveRecommendationsForUser = async (
  userId: string,
  items: any[]
) => {
  try {
    await Recommendation.create({
      userId,
      items,
    });

    logger.info("Recommendations stored successfully", { userId });
  } catch (error) {
    logger.error("Failed to store recommendations", { error, userId });
  }
};
